services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  # backend:
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0'
  #   volumes:
  #     - ./backend:/myapp
  #   environment:
  #     TZ: Asia/Tokyo
  #     RAILS_ENV: development
  #     # DB_HOST: db
  #     DB_USER: root
  #     # MYSQL_ROOT_PASSWORD:
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - db
  #   stdin_open: true
  #   tty: true

  backend-php:
    build:
      context: ./backend-php
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend-php:/var/www/html
    command: php-fpm
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "3002:80"
    volumes:
      - ./backend-php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-php

  # frontend:
  #   build: 
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/frontend
  #   command: yarn run serve
  #   ports:
  #     - 81:8080
  #   depends_on:
  #     - backend
  #   stdin_open: true
  #   tty: true
    
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    volumes:
      - ./frontend-react:/frontend-react
    command: yarn run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend-php
    stdin_open: true
    tty: true
    
volumes:
  postgres_volume:
