FROM php:8.2-fpm-alpine

RUN apk add --no-cache \
    git \
    unzip \
    zip \
    postgresql-dev \
    && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

EXPOSE 9000
